[package]
name = "hello-template"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
pcap-file = "1.1"
pnet_packet = "0.34"

# Dependencia para la captura de paquetes.
# pcap = "0.10" # Deshabilitado temporalmente

[build-dependencies]
