[package]
name = "bo-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "bo_core"
path = "src/lib.rs"

[dependencies]
bytes = "1.4"
thiserror = "1.0"
hkdf = "0.12"
sha2 = "0.10"
tokio = { version = "1", features = ["rt", "net", "macros", "io-util"] }
async-trait = "0.1"

[dev-dependencies]


